apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-bentivi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bentivi-dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: k8s-bentivi-dev
    spec:
      containers:
      - name: k8s-bentivi-dev
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 100Mi
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5000
