apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-bentivi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bentivi-dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: k8s-bentivi-dev
    spec:
      containers:
      - name: k8s-bentivi-dev
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - name: http
        - containerPort: 5000
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            memory: 128Mi
            cpu: 100m