apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backoffice-dev-virtualservice
  namespace: develop  
spec:
  hosts:
  - "backoffice-dev.pbuilders.io"
  gateways:
  - backoffice-dev-gateway
  http:
  - route:
    - destination:
        host: k8s-bentivi-dev
        port:
          number: 80 
