apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backoffice-deployment-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backoffice-development
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: backoffice-development
    spec:
      containers:
      - name: backoffice-development
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 100Mi
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
