apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: backoffice-dev-cert
  namespace: istio-system
spec:
  secretName: backoffice-dev-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: backoffice-dev.pbuilders.io
  dnsNames:
  - backoffice-dev.pbuilders.io